development:
  adapter: mysql
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
  username: vulnshop
  password: very_secure_password
  database: vulnshop
test:
  adapter: mysql
  host: localhost
  username: travis
  database: vulnshop

